use_frameworks!

platform :ios, '9.0'

target 'testForKwalee_Example' do
  pod 'testForKwalee', :path => '../'
  pod 'IronSourceSDK','6.8.4.0'
  pod 'IronSourceAdColonyAdapter','4.1.5.1'
  pod 'IronSourceAdMobAdapter','4.3.4.1'
  pod 'IronSourceAmazonAdapter','4.3.0.1'
  pod 'IronSourceAppLovinAdapter','4.3.3.2'
  pod 'IronSourceChartboostAdapter','4.1.6.1'
  pod 'IronSourceFacebookAdapter','4.3.4.2'

  pod 'IronSourceHyprMXAdapter','4.1.2.1'
  pod 'IronSourceInMobiAdapter','4.3.1.2'
  pod 'IronSourceMaioAdapter','4.1.3.1'
  pod 'IronSourceTapjoyAdapter','4.1.3.2'
  pod 'IronSourceTikTokAdapter','4.1.0.1'
  pod 'IronSourceUnityAdsAdapter','4.1.2.4'
  pod 'IronSourceVungleAdapter','4.1.6.2'

  pod 'YumiMediationAdapters', :subspecs => ['Baidu','Domob','GDT','Mintegral','OneWay','ZplayAds']
  pod 'YumiMediationDebugCenter-iOS'

  target 'testForKwalee_Tests' do
    inherit! :search_paths

    
  end
end
